
name: Test Build

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# Set python environment
env:
  PYTHON_VERSION: 3.8

# Job Descriptions
jobs:
  code_analysis:
    name: Code Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Change Directory
        run: cd ${{ github.workspace }}
      - name: Package Setup
        run: make setup
      - name: Run Lint
        run: make lint
      - name: Validate Package Imports
        run: make validate
      - name: Run Tests
        run: make test


